### ISSUE TITLE
the result

### ISSUE THREAD

**Issue by liuyongming0612** [chadlaing/Panseq#23]
why the result of panGenome.fasta have so many sequence of "NNNN......."

**Comment by chadlaing** [comment]
Hi @liuyongming0612,

The pan-genome having so many Ns would be due to the input sequences having so many Ns. The Ns will show up as not-matching anything, and therefore be included in the pan-genome because they are "novel".

I would suggest either removing them from your input genomes, or the generated pan-genome.

I hope that helps,
Chad
